# Generated by Django 3.2.16 on 2022-11-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='std',
            field=models.IntegerField(),
        ),
    ]
